### ISSUE TITLE
Any type

### ISSUE THREAD

**Issue by Jaguar-515** [evaera/Cmdr#136]
The "any" type would be composed mostly of the [currently supported types](https://eryn.io/Cmdr/guide/Types.html) (or maybe all of the types?) in Cmdr. 

I propose this because while working on an implementation of #121, I realized it would be difficult without having an any type since the list could be made up of booleans, numbers, etc. 

This would be [similar to TypeScript's any type implementation](https://www.typescriptlang.org/docs/handbook/basic-types.html#any) (or something like that).

**Comment by evaera** [comment]
This doesn't make sense to me. Cmdr types are not algebraic so we can't really do this (we can't make a type out of other types). There is a proposal for a [`Variant`](https://github.com/evaera/Cmdr/issues/79) type, which could be similar, but the best alternative right now is the `string` type. Since the arguments are already strings, the `string` type is effectively a raw data pass through, i.e. no parsing.

**Comment by evaera** [comment]
#121 describes a few utility commands that could be used to operate on lists. There is no need for an *any* type here. You can just use the `string` type.
