### ISSUE TITLE
Hooks not working properly

### ISSUE THREAD

**Issue by Arekan** [evaera/Cmdr#27]
I may be doing something horribly wrong, but hooks don't seem to work properly and I can't create a permissions system because of it.
Trying to do it this way on the server:
```lua
local Cmdr = require(script.Cmdr)

Cmdr:AddHook("BeforeRun", function(context)
	print("test")
end)

Cmdr:RegisterDefaultCommands()
```
_'test'_ never gets printed on accurate play solo, or testing with 2 players.
This is using the .rbxm under release and seems to also apply to the RoStrap version.

**Comment by evaera** [comment]
Hey, I can't reproduce this. Could you please attach your place file so I can see what's going on?

**Comment by evaera** [comment]
Without seeing your file, the most likely cause I can think of is that the command you're testing it with is client-only. If you set the `Run` property in the command definition table instead of using a separate ModuleScript, that makes the command client only. Server hooks wouldn't run in this case. More info here:

https://github.com/evaera/Cmdr#run-function-context-commandcontext--any

**Comment by Arekan** [comment]
Yeah, I was using the blink command to test the hooks out, so it was never running past the server. Sorry about that.

**Comment by evaera** [comment]
No problem! I should update the docs to be more clear about this.

**Comment by evaera** [comment]
@Arekan Hey, I just updated the Hooks section and added a new function that will make it much easier to add a hook on the server and the client at the same time.

See here: https://github.com/evaera/Cmdr#beforerun

Thanks for the issue! That was definitely confusing before.
