### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#34]
- [x] brickColor, brickColors <https://gist.github.com/TripleFrequency/e43fe44d50d596634894ee236fdac71e>
- [x] duration, durations
- [x] brickColor3, brickColor3s - resolves into a Color3, but selected by brickColor name
- [x] teamColor, teamColors - resolves into BrickColor matching by team, uses that team's color
- [x] hexColor3, hexColor3s - resolve hex into Color3
- [x] color3, color3s (delineate by comma or spaces, checking comma first) - Color3
- [x] vector3, vector3s (delineate by comma or spaces, checking comma first) - Vector3
- [ ] time
- [x] integers
- [x] strings
- [x] numbers
- [x] booleans

**Comment by TripleFrequency** [comment]
Perhaps there could also be some types for time:
* duration - formatted like `4d`, `1h`, `1w2d1h`, etc.
* time - formatted roughly like ISO 8601: `2018-09-29T13:00:00.000Z`

The time type is clearly very complex for regular users, but perhaps there could be other formats for it, or you could use defaults. So, `2018-09-29` or `09/29/18` would work.

Both of these types should equate to durations in seconds, or time in epoch seconds (since Lua uses seconds instead of milliseconds).
