### ISSUE TITLE
Filesystem-like view of the game tree

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#78]
Optional command group consisting of commands for navigation and modification of the game tree.

evaera@DataModel `cd Workspace`
evaera@Workspace `ls` 
evaera@Workspace `prop Baseplate CanCollide false`
evaera@Workspace `rm Baseplate`

Potential commands `cd`, `pwd`, `rm`, `cp`, `mv`, `make <instance> [name]`, `prop <name> <property> [value to set]`

`prop`'s value parameter could use dynamic Type from #93

**Comment by LoganDark** [comment]
What exactly do you mean like this?

You mean like an in-game Explorer-type thing or what?

**Comment by Reshiram110** [comment]
I would definitely love to see this as a feature. Not only does it give some major bash/linux vibes, but it's really useful for debugging.

**Comment by Reshiram110** [comment]
Working on this!

One edge case I would like to point out, is that `game` is a reserved keyword.
So if there is a part named "game" under `game.Workspace`, doing the following won't work as expected:
```
cd Workspace
cd game
```
This will change the 'working director' back to `game`, instead of `game.Workspace.game`.
This applies to any of the 'linux commands' as it were.

**Comment by LoganDark** [comment]
@Reshiram110 `cd .game`

**Comment by Reshiram110** [comment]
> support `cd .game`
Could you clarify a bit more on this? Are you asking me to reserve ".game" as `game`, instead of "game"?
I.e. to switch to `game` you would run
```
cd Workspace
cd .game
```

**Comment by LoganDark** [comment]
`cd game` -> cd to datamodel
`cd .game` -> cd to the instance named "game" in the 'working directory'

**Comment by evaera** [comment]
With this change, I would like to rename the `SetPlaceName` function to `SetInputLabel`. The old `SetPlaceName` should be assigned to the new function so they both work.

**Comment by Reshiram110** [comment]
@evaera Is this what you were looking for? https://github.com/Reshiram110/Cmdr/commit/61307d03408accd724fd6e81514aa5254b580974

**Comment by LoganDark** [comment]
@evaera `SetPrompt` :<

**Comment by Reshiram110** [comment]
Personally, I find `SetPrompt` to be more clear and concise.

**Comment by evaera** [comment]
SetPrompt is better, let's use that

**Comment by Reshiram110** [comment]
The treeview now supports ls'ing/cd'ing on instances who's names are the same as a keywords!

I.e. if you have a part under `Workspace` named "game", you can cd to it/ls it via
```
cd Workspace
cd .game
```

This is the same as doing `cd ./SomeFolder` in bash.
It should be noted that "game" is a reserved keyword, so if you ran "cd game", the current working instance would be changed to the datamodel's root.
```
cd Workspace
cd game
```

**Comment by Reshiram110** [comment]
Just found an edge-case, if you `cd` into an instance (say `Workspace.Part` for example), then the instance gets deleted, any attempt to `ls` or `cd` with any relative path to the now deleted instance fails, and instead simply returns the standard "{Name} is not recognized as a valid instance".

I ran a quick experiment in linux bash, and it suffers from a similar problem:
![image](https://user-images.githubusercontent.com/26460940/68988702-7b06ea00-0809-11ea-8efa-b478f543536b.png)

This brings up the question of how we should handle cases where the current working instance has been deleted. Should we just `cd` back to `game`? I toyed with the idea of `cd`ing to the deleted instance's parent, but that isn't really feasible as the instance has been deleted..meaning its parent property no longer exists.

**Comment by Reshiram110** [comment]
So after some discussion with @evaera, it seems the best course to take here is to just handle the instance in a detached state until the developer `cd`'s back into the datamodel.

**Comment by Reshiram110** [comment]
Instances detached from the datamodel are now supported! If the currently active working instance is destroyed, a warning will be displayed in the terminal.

Here's a quick rough example of how the behavior looks:
```
Reshiram110@Game.Client:game.Workspace.Reshiram110.Head$ ls
Mesh
Neck
etc.
```

**I die, avatar is thus destroyed and parented to nil**

```
The current working instance has been destroyed, unexpectedbehavior may occur!

Reshiram110@Game.Client:Reshiram110.Head$ ls
The current working instance has been destroyed, unexpectedbehavior may occur!

Mesh
Neck
etc.
```

**A few seconds later, the garbage collector destroys the rest of the avatar except the head**

```
Reshiram110@Game.Client:Head$ cd Mesh
The current working instance has been destroyed, unexpectedbehavior may occur!

Reshiram110@Game.Client:Head.Mesh$
```

**Garbage collector destroys head**

```
Reshiram110@Game.Client:Mesh$
```

**Comment by LoganDark** [comment]
@Reshiram110 unexpectedbehavior 3 times, maybe you should fix that :)

I have a little proposal, if the current instance's parent is nil then don't allow `cd ..`

**Comment by Reshiram110** [comment]
> unexpectedbehavior 3 times, maybe you should fix that :)

I could limit it to display once, during the initial time the working instance has been destroyed instead of every time you `cd` or `ls` under a destroyed instance.

> if the current instance's parent is nil then don't allow `cd ..`

I don't see any benefit to dis-allowing commands to be ran while under a destroyed instance - if the developer is working under a destroyed instance, they may be doing it for debugging purposes or somesuch and thus limiting the behavior would only hinder them. Limiting the behavior would also force me to remove the generalized behavior of the code that resolves relative paths.
The only 'benefit' I see to doing this is to suppress the warning messages, which, as stated in my first response, can be easily changed.

> or cd ... to go up 2 directories and so on... you support that right? is useful!!!

This currently is not supported, `..` is used to traverse up one instance in a relative path. I'm not entirerly sure how I would implement something like this due to the structure of Roblox instance paths. Also, the syntax feels a bit weird to me - `cd ....` to go up 3 instances doesn't seem very ergonomic as there's nothing separating each individual `.`. In bash/windows you have `cd ../../../../`, but since we're wrapping around the structure of instances, we can't natively add a 'path separator', and not having one makes it hard to read where exactly you are navigating to.

**Comment by LoganDark** [comment]
> I could limit it to display once, during the initial time the working instance has been destroyed instead of every time you cd or ls under a destroyed instance.

I meant fix the typo! `unexpectedbehavior` is not a word

> I don't see any benefit to dis-allowing commands to be ran while under a destroyed instance

I never said that, I said `cd ..`, as in... don't allow the user to change their directory to nil.

**Comment by Reshiram110** [comment]
> I meant fix the typo! unexpectedbehavior is not a word. You pasted that in 3 times in your comment, didn't notice it, then I pointed it out, and you still didn't notice it? xD

Oh haha! I actually did notice it a few hours ago, but I was tired and was heading to bed so I didn't bother fixing it. I'll edit my post to correct the typo. :-)

> I never said that, I said cd .., as in... don't allow the user to change their directory to nil.
Ah ok. My code already handles this. Since `..` gets resolved to `Instance.Parent` in a relative path, if you `cd ..` while under `game` or the root of a detached instance, `ls`/`cd` will simply spit `'..' is not recognized as a valid instance` to the terminal, since `..` is `nil` in that case.

Example:
```
Reshiram110@Game.Client:game$ cd ..
'..' is not recognized as a valid instance.
Reshiram110@Game.Client:game$
```

**Comment by LoganDark** [comment]
> I'll edit my post to correct the typo. :-)

You already did. You should edit the code to correct the typo too. :P

**Comment by Reshiram110** [comment]
My code never had that typo, I typed the output examples by hand.

**Comment by LoganDark** [comment]
~So you made the same typo 3 times?~ Oh, okay, got it :p
